Eliminate clang compilation error due to redefined int
To support x86_64 based host, primitive type "int" was redefined as
"long". However, it would cause clag compilation error:
    first parameter of 'main' (argument count) must be of type 'int'

This patch attempts to exclude the definition for "int main()"